# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imageprocessing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imageprocessing.proto',
  package='imageprocessing',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15imageprocessing.proto\x12\x0fimageprocessing\"F\n\x05Image\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x32R\n\x0fImageProcessing\x12?\n\x0bToGrayscale\x12\x16.imageprocessing.Image\x1a\x16.imageprocessing.Image\"\x00\x32\\\n\x15ImageProcessingStream\x12\x43\n\x0bToGrayscale\x12\x16.imageprocessing.Image\x1a\x16.imageprocessing.Image\"\x00(\x01\x30\x01\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='imageprocessing.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='imageprocessing.Image.height', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='imageprocessing.Image.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channels', full_name='imageprocessing.Image.channels', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='imageprocessing.Image.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'imageprocessing_pb2'
  # @@protoc_insertion_point(class_scope:imageprocessing.Image)
  })
_sym_db.RegisterMessage(Image)



_IMAGEPROCESSING = _descriptor.ServiceDescriptor(
  name='ImageProcessing',
  full_name='imageprocessing.ImageProcessing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=114,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='ToGrayscale',
    full_name='imageprocessing.ImageProcessing.ToGrayscale',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_IMAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEPROCESSING)

DESCRIPTOR.services_by_name['ImageProcessing'] = _IMAGEPROCESSING


_IMAGEPROCESSINGSTREAM = _descriptor.ServiceDescriptor(
  name='ImageProcessingStream',
  full_name='imageprocessing.ImageProcessingStream',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=198,
  serialized_end=290,
  methods=[
  _descriptor.MethodDescriptor(
    name='ToGrayscale',
    full_name='imageprocessing.ImageProcessingStream.ToGrayscale',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_IMAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEPROCESSINGSTREAM)

DESCRIPTOR.services_by_name['ImageProcessingStream'] = _IMAGEPROCESSINGSTREAM

# @@protoc_insertion_point(module_scope)
