# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import imageprocessing_pb2 as imageprocessing__pb2


class ImageProcessingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ToGrayscale = channel.unary_unary(
        '/imageprocessing.ImageProcessing/ToGrayscale',
        request_serializer=imageprocessing__pb2.Image.SerializeToString,
        response_deserializer=imageprocessing__pb2.Image.FromString,
        )


class ImageProcessingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ToGrayscale(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageProcessingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ToGrayscale': grpc.unary_unary_rpc_method_handler(
          servicer.ToGrayscale,
          request_deserializer=imageprocessing__pb2.Image.FromString,
          response_serializer=imageprocessing__pb2.Image.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'imageprocessing.ImageProcessing', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
