# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imageprocessing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15imageprocessing.proto\x12\x0fimageprocessing\"F\n\x05Image\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x32R\n\x0fImageProcessing\x12?\n\x0bToGrayscale\x12\x16.imageprocessing.Image\x1a\x16.imageprocessing.Image\"\x00\x62\x06proto3')



_IMAGE = DESCRIPTOR.message_types_by_name['Image']
Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'imageprocessing_pb2'
  # @@protoc_insertion_point(class_scope:imageprocessing.Image)
  })
_sym_db.RegisterMessage(Image)

_IMAGEPROCESSING = DESCRIPTOR.services_by_name['ImageProcessing']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE._serialized_start=42
  _IMAGE._serialized_end=112
  _IMAGEPROCESSING._serialized_start=114
  _IMAGEPROCESSING._serialized_end=196
# @@protoc_insertion_point(module_scope)
