# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import imagestreamprocessing_pb2 as imagestreamprocessing__pb2


class ImageStreamProcessingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ToGrayscale = channel.stream_stream(
                '/imagestreamprocessing.ImageStreamProcessing/ToGrayscale',
                request_serializer=imagestreamprocessing__pb2.Image.SerializeToString,
                response_deserializer=imagestreamprocessing__pb2.Image.FromString,
                )


class ImageStreamProcessingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ToGrayscale(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageStreamProcessingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ToGrayscale': grpc.stream_stream_rpc_method_handler(
                    servicer.ToGrayscale,
                    request_deserializer=imagestreamprocessing__pb2.Image.FromString,
                    response_serializer=imagestreamprocessing__pb2.Image.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imagestreamprocessing.ImageStreamProcessing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageStreamProcessing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ToGrayscale(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/imagestreamprocessing.ImageStreamProcessing/ToGrayscale',
            imagestreamprocessing__pb2.Image.SerializeToString,
            imagestreamprocessing__pb2.Image.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
