# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagestreamprocessing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bimagestreamprocessing.proto\x12\x15imagestreamprocessing\"F\n\x05Image\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x32h\n\x15ImageStreamProcessing\x12O\n\x0bToGrayscale\x12\x1c.imagestreamprocessing.Image\x1a\x1c.imagestreamprocessing.Image\"\x00(\x01\x30\x01\x62\x06proto3')



_IMAGE = DESCRIPTOR.message_types_by_name['Image']
Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'imagestreamprocessing_pb2'
  # @@protoc_insertion_point(class_scope:imagestreamprocessing.Image)
  })
_sym_db.RegisterMessage(Image)

_IMAGESTREAMPROCESSING = DESCRIPTOR.services_by_name['ImageStreamProcessing']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE._serialized_start=54
  _IMAGE._serialized_end=124
  _IMAGESTREAMPROCESSING._serialized_start=126
  _IMAGESTREAMPROCESSING._serialized_end=230
# @@protoc_insertion_point(module_scope)
